# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Authorization.create([
  { :user_id => 1, :role_id => 1, :created_at => "2013-06-10 19:18:31", :updated_at => "2013-06-10 19:18:31" }
], :without_protection => true )



Enrolment.create([
  { :team_id => nil, :person_id => nil, :teamrole => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Event.create([
  { :name => "Cleanup", :description => "yeah let's clean up!", :start => "2013-06-05 18:00:00", :end => "2013-06-05 19:00:00", :in_series => false, :address => "123 Main St.", :vol_need => 5, :created_at => "2013-06-05 04:17:20", :updated_at => "2013-06-05 04:17:20", :organization_id => 1, :team_id => nil },
  { :name => "event Y", :description => "", :start => "2013-06-09 17:00:00", :end => "2013-06-09 18:00:00", :in_series => false, :address => "", :vol_need => 5, :created_at => "2013-06-09 17:43:01", :updated_at => "2013-06-09 17:43:01", :organization_id => 1, :team_id => nil },
  { :name => "SC gala", :description => "", :start => "2013-06-09 17:00:00", :end => "2013-06-10 17:00:00", :in_series => false, :address => "", :vol_need => 5, :created_at => "2013-06-09 17:44:33", :updated_at => "2013-06-09 17:44:33", :organization_id => 1, :team_id => nil },
  { :name => "SC gala 1", :description => "", :start => "2013-06-09 17:00:00", :end => "2013-06-09 17:00:00", :in_series => false, :address => "", :vol_need => 11, :created_at => "2013-06-09 17:47:55", :updated_at => "2013-06-09 17:47:55", :organization_id => 1, :team_id => nil },
  { :name => "an event", :description => "", :start => "2013-06-10 18:00:00", :end => "2013-06-10 18:00:00", :in_series => false, :address => "", :vol_need => 5, :created_at => "2013-06-10 18:19:34", :updated_at => "2013-06-10 18:19:34", :organization_id => 1, :team_id => nil },
  { :name => "ymca event 1", :description => "", :start => "2013-06-11 04:00:00", :end => "2013-06-11 04:00:00", :in_series => false, :address => "", :vol_need => 4, :created_at => "2013-06-11 04:47:45", :updated_at => "2013-06-11 04:47:45", :organization_id => 2, :team_id => nil }
], :without_protection => true )



OrgTeam.create([
  { :organization_id => nil, :team_id => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Organization.create([
  { :name => "Sierra Club", :created_at => "2013-06-05 04:14:51", :updated_at => "2013-06-05 04:14:51" }
], :without_protection => true )



Person.create([
  { :name => nil, :online_uris => [], :created_at => nil, :updated_at => nil }
], :without_protection => true )



Role.create([
  { :name => "admin", :created_at => "2013-06-10 19:17:03", :updated_at => "2013-06-10 19:17:03" }
], :without_protection => true )



Shift.create([
  { :name => nil, :description => nil, :start => nil, :end => nil, :in_series => nil, :address => nil, :vol_need => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Team.create([
  { :name => "A Club Team", :organization_id => 1, :created_at => "2013-06-09 03:53:22", :updated_at => "2013-06-11 03:46:01", :event_id => 1 },
  { :name => "team X", :organization_id => 2, :created_at => "2013-06-09 17:29:19", :updated_at => "2013-06-11 04:47:45", :event_id => 15 },
  { :name => "ywca gala organizers", :organization_id => 2, :created_at => "2013-06-09 17:44:33", :updated_at => "2013-06-11 03:46:25", :event_id => nil },
  { :name => "A club soda", :organization_id => 1, :created_at => "2013-06-09 17:47:55", :updated_at => "2013-06-11 03:46:12", :event_id => nil }
], :without_protection => true )



User.create([
  { :created_at => "2013-06-10 19:18:12", :updated_at => "2013-06-10 19:21:54", :email => "admin@eventually.org", :encrypted_password => "$2a$10$HR8CkQpPCtqo7b2KCUx.neOAT37Pj/1kjrs/sKWXZCSswEm/NM1ra", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 2, :current_sign_in_at => "2013-06-10 19:21:54", :last_sign_in_at => "2013-06-10 19:18:12", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :name => "admin", :organization_id => nil },
  { :created_at => "2013-06-10 19:50:03", :updated_at => "2013-06-11 04:53:29", :email => "sierraclub@eventually.org", :encrypted_password => "$2a$10$rpODYFckYhQn68r2LjL2J.4PneQEfP1FmviinDdK5jknKcLCbbRQW", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 6, :current_sign_in_at => "2013-06-11 04:53:29", :last_sign_in_at => "2013-06-11 04:01:10", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :name => "sierraclub", :organization_id => 1 },
  { :created_at => "2013-06-11 03:01:41", :updated_at => "2013-06-11 04:53:40", :email => "ymca@eventually.org", :encrypted_password => "$2a$10$Bq4mAzSso0UT5LbJq4zyG.dtVcJlu.IwTNiQIN7O0VCUeDSxN/5rm", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 4, :current_sign_in_at => "2013-06-11 04:53:40", :last_sign_in_at => "2013-06-11 04:19:07", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :name => "ymca", :organization_id => 2 }
], :without_protection => true )


